CREATE TABLE IF NOT EXISTS `profile_builder_websiteprofile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `website` varchar(200) NOT NULL,
  `phone_no` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `address` longtext NOT NULL,
  `vendor_creation_timestamp` datetime NOT NULL,
  `website_title` longtext NOT NULL,
  `website_description` longtext NOT NULL,
  `website_keywords` longtext NOT NULL,
  `website_contact` varchar(255) NOT NULL,
  `website_clients` varchar(255) NOT NULL,
  `website_portfolio` varchar(255) NOT NULL,
  `website_testimonial` varchar(255) NOT NULL,
  `linkedin_profile` varchar(200) NOT NULL,
  `facebook_profile` varchar(200) NOT NULL,
  `twitter_profile` varchar(200) NOT NULL,
  `website_type` varchar(255) NOT NULL,
  `linkedin_description` longtext NOT NULL,
  `linkedin_id` int(11) NOT NULL,
  `linkedin_followers` int(11) NOT NULL,
  `linkedin_headcount` varchar(100) NOT NULL,
  `linkedin_foundedyear` int(11) NOT NULL,
  `linkedin_speciality` longtext NOT NULL,
  `linkedin_city` varchar(100) NOT NULL,
  `linkedin_company_id` int(11) NOT NULL,
  `linkedin_company_type` varchar(100) NOT NULL,
  `alexa` int(11) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `company_logo` varchar(255) NOT NULL,
  `fb_likes` int(11) NOT NULL,
  `website_status` int(11) NOT NULL,
  `facebook_status` int(11) NOT NULL,
  `linkedin_status` int(11) NOT NULL,
  `alexa_status` int(11) NOT NULL,
  `logo_status` int(11) NOT NULL,
  `twitter_status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `website` (`website`),
  KEY `profile_builder_websiteprofile_d01a57d6` (`company_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;